### ISSUE TITLE
请问有小程序端的蓝牙通信协议有嘛？

### ISSUE THREAD

**Issue by ycb0318** [YolandaQingniu/qnscalesdk#3]

**Comment by chztp** [comment]
https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wx2a4ca48ed5e96748&token=1470542861&lang=zh_CN

**Comment by ycb0318** [comment]
> https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wx2a4ca48ed5e96748&token=1470542861&lang=zh_CN

谢谢

**Comment by ycb0318** [comment]
> https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wx2a4ca48ed5e96748&token=1470542861&lang=zh_CN

谢谢
