### ISSUE TITLE
listener	QNBleStateListener	监听器，包含一个方法,扫描到设备时会在这个对象中进行回调。

### ISSUE THREAD

**Issue by sbbqq** [YolandaQingniu/qnscalesdk#5]
listener | QNBleStateListener | 监听器，包含一个方法,扫描到设备时会在这个对象中进行回调。
-- | -- | --

文档是否有错，这不应该是监听设置蓝牙设备状态变化的吗？怎么和文档下面那个扫描的混淆了？

**Comment by chztp** [comment]
是的，文档描述有问题，感谢指正，这个是监听是包含系统蓝牙状态变化的回调
