### ISSUE TITLE
 测试appid问题

### ISSUE THREAD

**Issue by sbbqq** [YolandaQingniu/qnscalesdk#6]
您好，我这边用的测试id12345678,开始还能返回除了bmi和体重的的信息，后续返回不了了？是因为测试帐号的问题吗

**Comment by YolandaQingniu** [comment]
123456789这个账号是测试账号，建议接入的话直接申请正式账号。你的这种情况有可能是自身测量的问题，如果要得到其他的信息需要光脚测量。
