### ISSUE TITLE
Cannot get body fat data

### ISSUE THREAD

**Issue by Pypey85** [YolandaQingniu/qnscalesdk#7]
I can get weight data, but after the scales device completes it's body scan, the following exception is thrown

No implementation found for void com.qingniu.scale.model.BleScaleData.initWithAthlete(int, int, int, int, int) (tried Java_com_qingniu_scale_model_BleScaleData_initWithAthlete and Java_com_qingniu_scale_model_BleScaleData_initWithAthlete__IIIII)

Using version 2.2.6

Any thoughts or help?

**Comment by chztp** [comment]
This is a problem with your local configuration. Please follow the local configuration instructions for configuration. Online configuration is recommended.
